# Generated by Django 4.2.1 on 2023-06-12 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_sent'),
            preserve_default=False,
        ),
    ]
